### ISSUE TITLE
Addon can't be installed on HASSIO on RaspberyPi 1B+

### ISSUE THREAD

**Issue by Shamane2000** [marthoc/hassio-addons#24]
On a new setup of HASSIO i try to install the deCONZ Addon from here, exsactly as given in the installation instructions. But after click "Install" in the Addon installer and waiting some circles, the button blinks red for a short moment and it stops with following log output:

`
...
2018-10-17 11:17
53 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=2 from 2018-10-17 10:25:50.055574)
2018-10-17 11:18:08 WARNING (MainThread) [homeassistant.setup] Setup of recorder is taking over 10 seconds.
2018-10-17 11:18:08 WARNING (MainThread) [homeassistant.setup] Setup of frontend is taking over 10 seconds.
2018-10-17 11:18:36 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-10-17 11:18:43 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-10-17 11:18:57 WARNING (SyncWorker_4) [plexapi] BadRequest (401) unauthorized http://192.168.178.52:32400/; <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
2018-10-17 11:45:30 WARNING (MainThread) [homeassistant.components.group] remove:Group 'all_scripts' doesn't exist!
2018-10-17 11:51:11 WARNING (MainThread) [homeassistant.components.group] remove:Group 'all_scripts' doesn't exist!
2018-10-17 11:56:31 WARNING (MainThread) [homeassistant.components.group] remove:Group 'all_scripts' doesn't exist!
2018-10-17 11:58:37 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /homeassistant/check request
2018-10-17 11:58:38 ERROR (MainThread) [homeassistant.components.hassio] Error on Hass.io API: 
2018-10-17 11:58:38 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall homeassistant.restart (c:0776ad43f92648938aa1181928063812)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/__init__.py", line 264, in async_handle_core_service
    error = await async_check_config(hass)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/__init__.py", line 147, in async_check_config
    if result['result'] == "error":
UnboundLocalError: local variable 'result' referenced before assignment
2018-10-17 12:03:04 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
`

My System are: 
RaspberryPi 1 B+
DE ConBee USB Stick (tested with and without additional Power source)
(No optional USB Stick)
System: HassOS 1.11
Deployment: production
HASSIO Addons: 
- deCONZ 2.05.39 
- Configurator 2

I don't know where to find more logs, so maybe I could provide more Informations, if I Know where to find them.

**Comment by Shamane2000** [comment]
Some additional info, after restart the whole system, it seems the plugin is installed, because now the addon shows the button uninstall and start. so I configured my USB ("/dev/ttyUSB0") in the plugin and start (I also restartet also the rpi after that) but the addon doesn't start. 
I don't find any log output for that timestamp...

**Comment by marthoc** [comment]
Unfortunately the log output you posted is unrelated to deconz. Under the Hass.io menu, go to System to see the log that will give a better idea of addon errors. Generally speaking, you’ll struggle with Hass.io on anything less than RPi 3B.
