### ISSUE TITLE
'NoneType' object has no attribute 'async_update'

### ISSUE THREAD

**Issue by mpertsov** [marthoc/hassio-addons#5]
Hi there!

First of all, thanks for efforts making this add-on 👍 

Recently I got RaspBee, therefore installed this add-on on my RPi3 running hass.io 0.65.6.
In logs I can observe some exception fired periodically:
````
Unhandled error in exception handler
context: {'exception': AttributeError("'NoneType' object has no attribute 'async_update'",)}
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 784, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/handles/stream.pyx", line 563, in uvloop.loop.UVStream._on_read
  File "/usr/lib/python3.6/site-packages/pydeconz/websocket.py", line 98, in data_received
    self.async_callback(payload)
  File "/usr/lib/python3.6/site-packages/pydeconz/__init__.py", line 159, in async_event_handler
    self.sensors[event['id']].async_update(event)
AttributeError: 'NoneType' object has no attribute 'async_update'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/loop.pyx", line 2062, in uvloop.loop.Loop.call_exception_handler
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 94, in async_loop_exception_handler
    _LOGGER.error("Error doing job: %s", context['message'], **kwargs)
KeyError: 'message'
````

Hardware connected to RaspBee: 3 Phillips Hue "white ambiance" light bulbs and Hue Remote.

Please tell me if I can provide some more information to solve this issue.

Thank you.

**Comment by marthoc** [comment]
Unfortunately, this error is related to HA generally and isn’t specific to this Hass.io Add-on. You should open this as an issue on the main Home Assistant repo. Closing here for now.
